export const LOGIN_REQUEST="LOGIN_REQUEST";
export const LOGIN_SUCCESS="LOGIN_SUCCESS";
export const LOGIN_Fail="LOGIN_Fail";


export const REGISTER_USER_REQUEST="REGISTER_USER_REQUEST";
export const REGISTER_USER_SUCCESS="REGISTER_USER_SUCCESS";
export const REGISTER_USER_Fail="REGISTER_USER_Fail";


export const LOAD_USER_REQUEST="LOAD_USER_REQUEST";
export const LOAD_USER_SUCCESS="LOAD_USER_SUCCESS";
export const LOAD_USER_Fail="LOAD_USER_Fail";



export const UPDATE_PROFILE_REQUEST="UPDATE_PROFILE_REQUEST";
export const UPDATE_PROFILE_SUCCESS="UPDATE_PROFILE_SUCCESS";
export const UPDATE_PROFILE_RESET="UPDATE_PROFILE_RESET";
export const UPDATE_PROFILE_Fail="UPDATE_PROFILE_Fail";


export const UPDATE_PASSWORD_REQUEST="UPDATE_PASSWORD_REQUEST";
export const UPDATE_PASSWORD_SUCCESS="UPDATE_PASSWORD_SUCCESS";
export const UPDATE_PASSWORD_RESET="UPDATE_PASSWORD_RESET";
export const UPDATE_PASSWORD_Fail="UPDATE_PASSWORD_Fail";


export const FORGOT_PASSWORD_REQUEST="FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_SUCCESS="FORGOT_PASSWORD_REQUEST";
export const FORGOT_PASSWORD_Fail="FORGOT_PASSWORD_REQUEST";

export const NEW_PASSWORD_REQUEST="NEW_PASSWORD_REQUEST";
export const NEW_PASSWORD_SUCCESS="NEW_PASSWORD_SUCCESS";
export const NEW_PASSWORD_Fail="NEW_PASSWORD_Fail";



export const LOGOUT_SUCCESS="LOGOUT_SUCCESS";
export const LOGOUT_FAIL="LOGOUT_FAIL";

export const CLEAR_ERROR="CLEAR_ERROR";




